apiVersion: v1
kind: Namespace
metadata:
  name: agentgateway-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway
  labels:
    app: agentgateway
  namespace: agentgateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentgateway
  template:
    metadata:
      labels:
        app: agentgateway
    spec:
      containers:
        - name: agentgateway
          image: ghcr.io/agentgateway/agentgateway:0.6.1-ext
#          env:
#            - name: RUST_LOG
#              value: debug
          args:
            - -f
            - /etc/config/config.yaml
          ports:
            - containerPort: 8080 # Bind port
              name: bind
            - containerPort: 15000 # Admin port
              name: admin
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: agentgateway-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-config
  namespace: agentgateway-system
data:
  config.yaml: |-
    binds:
      - port: 8080
        listeners:
          - routes:
              - backends:
                  - mcp:
                      name: default
                      targets:
                        - name: everything
                          stdio:
                            args:
                              - '@modelcontextprotocol/server-everything'
                            cmd: npx
                policies:
                  cors:
                    allowCredentials: true
                    allowHeaders:
                      - mcp-protocol-version
                      - content-type
                      - authorization
                    allowMethods: [ ]
                    allowOrigins:
                      - '*'
                    exposeHeaders: [ ]
                  extAuthz:
                    context: {}
                    target: kyverno-authz-server.kyverno:9081

---
apiVersion: v1
kind: Service
metadata:
  name: agentgateway
  labels:
    app: agentgateway
  namespace: agentgateway-system
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: bind
      targetPort: bind
      protocol: TCP
    - port: 15000
      targetPort: admin
      protocol: TCP
      name: name
  selector:
    app: agentgateway
